export const projects = [
  {
    id: '1',
    title: 'An Hospital Website',
    info: 'A single page website built with react & bootstrap',
    technologies: 'React Bootstrap CSS',
    url: 'https://charismedhospital.com',
  },
  {
    id: '2',
    title: 'Job Search Application',
    info: 'A job search application for software developers',
    technologies: 'Node.js MongoDB Express React',
    url: 'https://devportals.herokuapp.com/',
    repo: 'https://github.com/Ademayowa/job_app_v1',
  },
  {
    id: '3',
    title: 'Movie Trailer App',
    technologies: 'Next.js TailwindCSS TMDB-API',
    info: 'A Movie Trailer Application',
    url: 'https://movie-trailers-three.vercel.app/',
    repo: 'https://github.com/Ademayowa/movie-trailers',
  },
  // {
  //   id: '4',
  //   title: 'Real Estate App',
  //   technologies: 'React Nextjs RapidAPI',
  //   info: 'A simple facebook web app clone built with react & firebase',
  //   url: 'https://prodfacebook-clone.web.app/',
  //   repo: 'https://github.com/Ademayowa/twitter-demo-firebase',
  // },
  {
    id: '5',
    title: 'LinkedIn Profile Dashboard',
    info: 'LinkedIn dashboard clone built with react & flexbox',
    technologies: 'React Tailwind CSS',
    url: 'https://linkedin-demo.netlify.app/',
    repo: 'https://github.com/Ademayowa/linkedin-clone',
  },
  {
    id: '6',
    title: 'This current website',
    technologies: 'React Bootstrap CSS',
    info: 'My portfolio website',
    url: 'https://mayorstacks.netlify.app/',
    repo: 'https://github.com/Ademayowa/portfolio-website-v1',
  },
];
